// Package ddl provides convenience helpers for applying SQLite DDL using a
// storage.Repository.
package ddl

import (
	"context"

	gddl "etl/internal/ddl"
	"etl/internal/storage"
)

// EnsureTable creates the target SQLite table if it does not already exist.
//
// It is idempotent and simply executes the CREATE TABLE IF NOT EXISTS
// statement generated by BuildCreateTableSQL via repo.Exec.
func EnsureTable(ctx context.Context, repo storage.Repository, def gddl.TableDef) error {
	sql, err := BuildCreateTableSQL(def)
	if err != nil {
		return err
	}
	return repo.Exec(ctx, sql)
}
