# cmd/linediff/Dockerfile
FROM golang:1.25-alpine AS builder
WORKDIR /src
COPY . .
RUN go build -o /linediff cmd/linediff/main.go
#RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
#    go build -trimpath -ldflags="-s -w" \
#    -o /out/importer ./cmd/importer


FROM alpine:3.22
COPY --from=builder /linediff /linediff
ENTRYPOINT ["/linediff"]

